-- A device-flow sign-in, parked here so the browser can show the code the CLI was given.
--
-- The CLI asks GitHub for a device code and gets two things back: a `user_code` the person
-- types, and a `device_code` that polls for the token. Only the first is written here. The
-- second never leaves the machine that asked for it — it is the credential, and a row in this
-- table is readable by anyone holding the id, so putting it here would turn a convenience into
-- a way to steal a sign-in.
--
-- The id is a capability: whoever has it sees the code. It is 32 random bytes generated by the
-- CLI, which is the only thing standing between this row and a stranger, so nothing that is
-- not already printed in the user's own terminal belongs in it.
CREATE TABLE login_sessions (
  -- 64 hex characters from the CLI's CSPRNG. Not a serial: a guessable id would let anyone
  -- watch a stranger's sign-in and race them to the code.
  id          text        PRIMARY KEY CHECK (id ~ '^[0-9a-f]{64}$'),
  -- What GitHub asked the person to type. Useless on its own: entering it authorises the
  -- device that requested it, which is the machine running the CLI, not the reader.
  user_code   text        NOT NULL CHECK (length(user_code) <= 32),
  -- Where GitHub wants it typed. Stored rather than assumed so an enterprise host works.
  verify_url  text        NOT NULL CHECK (length(verify_url) <= 400),
  created_at  timestamptz NOT NULL DEFAULT now(),
  -- GitHub's own expiry for the device code, so the page can stop offering a dead code.
  expires_at  timestamptz NOT NULL,
  -- Set by the CLI when GitHub hands it the token, so the page can say so and stop polling.
  -- The page finding out is a courtesy; the sign-in completes whether anyone is watching.
  handle      citext
);

-- Sweeping is by age, so that is what gets the index.
CREATE INDEX login_sessions_expiry ON login_sessions (expires_at);

-- Same posture as every other table: no direct client access, only the server's role.
ALTER TABLE login_sessions ENABLE ROW LEVEL SECURITY;
