#!/usr/bin/env node
/**
 * Regenerate `src/prices.json` from LiteLLM's public price map.
 *
 * Run by a maintainer, never by the CLI. tokenstats's whole claim is that it reads local
 * files and talks to nobody, so the price table ships vendored — a card must render the
 * same on a plane as it does online, and a pricing lookup at sync time would be a network
 * call users did not ask for.
 *
 *   node packages/core/scripts/refresh-prices.mjs
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SOURCE =
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";

/** Providers whose models can plausibly appear in a local coding-agent transcript. */
const PROVIDERS = new Set([
  "anthropic",
  "openai",
  "gemini",
  "vertex_ai-language-models",
  "xai",
  "mistral",
  "deepseek",
  "groq",
]);

const perMillion = (n) => (typeof n === "number" ? Math.round(n * 1e6 * 1e6) / 1e6 : 0);

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`${SOURCE} responded ${res.status}`);
const raw = await res.json();

const prices = {};
for (const [model, spec] of Object.entries(raw)) {
  if (model === "sample_spec" || typeof spec !== "object" || spec === null) continue;
  if (spec.mode !== "chat" || !PROVIDERS.has(spec.litellm_provider)) continue;
  if (typeof spec.input_cost_per_token !== "number") continue;

  // Strip the provider prefix LiteLLM uses for routing ("anthropic/claude-opus-5"); agents
  // log the bare model id.
  const id = model.includes("/") ? model.slice(model.lastIndexOf("/") + 1) : model;
  if (prices[id]) continue;

  prices[id] = {
    input: perMillion(spec.input_cost_per_token),
    output: perMillion(spec.output_cost_per_token),
    cacheWrite: perMillion(spec.cache_creation_input_token_cost ?? spec.input_cost_per_token),
    cacheRead: perMillion(spec.cache_read_input_token_cost ?? spec.input_cost_per_token),
  };
}

const out = {
  $comment:
    "Generated by scripts/refresh-prices.mjs from LiteLLM. USD per million tokens. Do not edit by hand.",
  $source: SOURCE,
  $generated: new Date().toISOString().slice(0, 10),
  prices: Object.fromEntries(Object.entries(prices).sort(([a], [b]) => a.localeCompare(b))),
};

const target = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "prices.json");
await writeFile(target, `${JSON.stringify(out, null, 2)}\n`);
console.log(`wrote ${Object.keys(prices).length} models to ${target}`);
